### ISSUE TITLE
SCP fails with non usefull errormessage

### ISSUE THREAD

**Issue by The1andONLYdave** [dprandzioch/avocado#23]
If remote file can't be written because of no space left on device avodeploy -d raises following error. 
Maybe mention this in docs or add different errormessages?
(second line is added by me to see full destination path)
-----------
I, [2015-01-20T16:32:22.758867 #29079]  INFO -- : started upload of file deploy.tar.gz to web
I, [2015-01-20T16:32:22.758943 #29079]  INFO -- : DBG: remote /tmp/deploy.tar.gz
/home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command': SCP did not finish successfully (1):  (Net::SCP::Error)
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:591:in `call'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:591:in `do_close'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:586:in `channel_close'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:118:in `close'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh.rb:212:in `ensure in start'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/net-ssh-2.9.1/lib/net/ssh.rb:212:in `start'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/task/local_task_execution_environment.rb:75:in `copy_to_target'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/strategy/local_copy.rb:96:in `block (3 levels) in <top (required)>'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/strategy/local_copy.rb:95:in `each_pair'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/strategy/local_copy.rb:95:in `block (2 levels) in <top (required)>'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/task/task.rb:82:in `instance_eval'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/task/task.rb:82:in `invoke'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/task/task_manager.rb:201:in `invoke_task'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/task/task_manager.rb:121:in `block in invoke_task_chain_containing'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/task/task_manager.rb:120:in `each_pair'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/lib/avodeploy/task/task_manager.rb:120:in `invoke_task_chain_containing'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/bin/avo:49:in `start'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/gems/avodeploy-0.5/bin/avo:132:in `<top (required)>'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/bin/avo:23:in `load'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/bin/avo:23:in `<main>'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	from /home/david-lee/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dprandzioch** [comment]
@The1andONLYdave  i'd prefer to check the most common risks, including disk usage, before starting the actual deployment to make the process as solid as possible because this is what a deployment system is meant for. What about a check for a minimum disk space of (deployment-size * 4)? -> tarball archive + /tmp-space to extract + extracted files + a little buffer
